#+TITLE: Emacs config file in org format
#+AUTHOR: John Lord
#+PROPERTY: header-args :results silent :tangle "/var/home/john/.emacs.d/init.el"
#+STARTUP: overview

* Init load time

Add a hook that reports how long and how many garbage collections the startup took. The hook is run at the very end, so the message doesn't get clobbered by other messages during startup.

#+begin_src emacs-lisp
  (add-hook 'emacs-startup-hook
            (lambda ()
              (message "Emacs ready in %s with %d garbage collections."
                       (format "%.2f seconds"
                               (float-time
                                (time-subtract after-init-time before-init-time)))
                       gcs-done)))
#+end_src

* Package Management

Declare the package repositories.

#+begin_src elisp
  (require 'package)
  (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
#+end_src

Initialize the package system, refresh the list of packages and install =use-package= if needed.

#+begin_src emacs-lisp
  (package-initialize)
  (when (not package-archive-contents)
    (package-refresh-contents))
  (when (not (package-installed-p 'use-package))
    (package-install 'use-package))
#+end_src

Finally, load =use-package= and ensure packages are installed by default. Later, system packages and already installed packages can include an =:ensure nil= clause.

#+begin_src emacs-lisp
  (require 'use-package)
  (custom-set-variables '(use-package-always-ensure t))
  ;; (custom-set-variables '(use-package-always-ensure t)
  ;;                       '(use-package-verbose t))
#+end_src

* Global defaults and custom variables

Clean up the interface by removing the menu bar, tool bar, and scroll bars. Also, inhibit the startup screen and provide an empty scratch buffer.

#+begin_src elisp
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (custom-set-variables '(inhibit-startup-screen t)
                        '(initial-scratch-message ""))
#+end_src

Do not create backup files since files under version control. Also, move deleted files to system trash instead of deleting outright.

#+begin_src elisp
  (custom-set-variables '(delete-by-moving-to-trash t)
                        '(make-backup-files nil))
#+end_src

Move focus to help windows, which makes it easy to close them with a 'q'.

#+begin_src elisp
  (custom-set-variables '(help-window-select t))
#+end_src

Enable various non-beginner functions.

#+begin_src elisp
  (put 'narrow-to-region 'disabled nil)
#+end_src

Change =zap-to-char= binding to =zap-up-to-char= and bind =zap-to-char= to =M-Z=.

#+begin_src elisp
  (global-set-key "\M-z" 'zap-up-to-char)
  (global-set-key "\M-Z" 'zap-to-char)
#+end_src

Install =visual-fill-column= which allows sets the column width to the default column width instead of fitting to the window size.

#+begin_src elisp
  (use-package visual-fill-column
    :hook
    (visual-line-mode . visual-fill-column-mode))
#+end_src

Start the =protonmail-bridge= process, if not already started to ensure available for =mu4e= protonmail context.

#+begin_src elisp
  (call-process "protonmail-bridge" nil 0)
#+end_src

* Themes

Install =all-the-icons= which provides nice icons for the doom theme. Fonts need to be manually installed using =(all-the-icons-install-fonts)=.

#+begin_src elisp
  (use-package all-the-icons
    :defer t)
#+end_src

Install =doom-themes= and default to the *doom-one* theme.
   
#+begin_src elisp
  (use-package doom-themes
    :custom
    (doom-themes-enable-bold t)
    (doom-themes-enable-italic t)
    :config
    (load-theme 'doom-one t)
    ;; Corrects (and improves) org-mode's native fontification.
    (doom-themes-org-config)
    )
#+end_src

** Install doom-modeline
   
#+begin_src elisp
  (use-package doom-modeline
    :hook
    (after-init . doom-modeline-mode)
    )
#+end_src

** Auth-Source-Pass
#+name: auth-source-pass
#+begin_src elisp
  (use-package auth-source-pass
    :defer t
    :custom
    (auth-source-debug t)
    (auth-source-do-cache nil)
    (auth-sources '(password-store))
    :init
    (auth-source-pass-enable)
    )
#+end_src

** Visual Fill Column
#+begin_src elisp
  (use-package visual-fill-column
    :hook
    (visual-line-mode . visual-fill-column-mode)
    )
#+end_src
* Evil
#+name: evil
#+begin_src elisp :tangle no
  (use-package evil 
    :demand
    :init
    (setq evil-emacs-state-cursor '("red" box)
          evil-normal-state-cursor '("green" box)
          evil-visual-state-cursor '("orange" box)
          evil-insert-state-cursor '("red" bar)
          evil-replace-state-cursor '("red" bar)
          evil-operator-state-cursor '("red" hollow)
          )
    :custom
    (evil-want-C-i-jump nil)
    (evil-cross-lines t)
    (evil-want-keybinding nil)
    :bind (:map evil-normal-state-map
                ([remap evil-next-line] . evil-next-visual-line)
                ([remap evil-previous-line] . evil-previous-visual-line)
           :map evil-motion-state-map
                ([remap evil-next-line] . evil-next-visual-line)
                ([remap evil-previous-line] . evil-previous-visual-line)
         )
    :config
    (evil-mode 1)
    )
#+end_src

#+name: evil-collection
#+begin_src elisp :tangle no
  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init)
    )
#+end_src

Install =evil-org= after =org-mode= to provide evil bindings in =org-mode=.

#+begin_src elisp :tangle no
  (use-package evil-org
    :after org
    :hook
    (org-mode . (lambda () evil-org-mode))
    :config
    (require 'evil-org-agenda)
    (evil-org-agenda-set-keys)
    )
#+end_src

* Completions and Projects
** Company
#+begin_src elisp
  (use-package company
    :hook
    (after-init . global-company-mode)
    )
#+end_src

** Projectile
#+begin_src elisp
  (use-package projectile
    :config
    (projectile-mode) 
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :custom
    (projectile-project-search-path
     '(
       "~/org/"
       ("~/git/" . 1)
       ("~/Analysis/" . 1)
       ))
   )
#+end_src

** Vertico
#+begin_src elisp
  (use-package vertico
    :init
    (vertico-mode)
    )
#+end_src

** Orderless
#+begin_src elisp
  (use-package orderless
    :custom
    (completion-styles '(orderless))
    (orderless-component-separator "[ &]")
    :config
    (defun just-one-face (fn &rest args)
      (let ((orderless-match-faces [completions-common-part]))
        (apply fn args)))
    (advice-add 'company-capf--candidates :around #'just-one-face)
    )
#+end_src

** Which Key
#+begin_src elisp
  (use-package which-key
    :init
    (which-key-mode)
    )
#+end_src

** Marginalia
#+begin_src elisp
  (use-package marginalia
    :bind
    (:map minibuffer-local-map
          ("M-A" . marginalia-cycle))
    :init
    (marginalia-mode)
    )
#+end_src

** Embark
#+begin_src elisp
  (use-package embark
    :bind
    ("C-." . embark-act)         ;; pick some comfortable binding
    ("C-;" . embark-dwim)        ;; good alternative: M-.
    ("C-h B" . embark-bindings) ;; alternative for `describe-bindings'
    :init
    ;; Optionally replace the key help with a completing-read interface
    (setq prefix-help-command #'embark-prefix-help-command)
    :config
    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none)))))
#+end_src

** Consult
#+begin_src elisp
  ;; Example configuration for Consult
  (use-package consult
    :bind
    ("C-c h" . consult-history)
    ("C-c m" . consult-mode-command)
    ("C-c b" . consult-bookmark)
    ("C-c k" . consult-kmacro)
    ;; C-x bindings (ctl-x-map)
    ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
    ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
    ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
    ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
    ;; Custom M-# bindings for fast register access
    ("M-#" . consult-register-load)
    ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
    ("C-M-#" . consult-register)
    ;; Other custom bindings
    ("M-y" . consult-yank-pop)                ;; orig. yank-pop
    ("<help> a" . consult-apropos)            ;; orig. apropos-command
    ;; M-g bindings (goto-map)
    ("M-g e" . consult-compile-error)
    ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
    ("M-g g" . consult-goto-line)             ;; orig. goto-line
    ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
    ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
    ("M-g m" . consult-mark)
    ("M-g k" . consult-global-mark)
    ("M-g i" . consult-imenu)
    ("M-g I" . consult-imenu-multi)
    ;; M-s bindings (search-map)
    ("M-s f" . consult-find)
    ("M-s F" . consult-locate)
    ("M-s g" . consult-grep)
    ("M-s G" . consult-git-grep)
    ("M-s r" . consult-ripgrep)
    ("M-s l" . consult-line)
    ("M-s L" . consult-line-multi)
    ("M-s m" . consult-multi-occur)
    ("M-s k" . consult-keep-lines)
    ("M-s u" . consult-focus-lines)
    ;; Isearch integration
    ("M-s e" . consult-isearch)
    (:map isearch-mode-map
     ("M-e" . consult-isearch)                 ;; orig. isearch-edit-string
     ("M-s e" . consult-isearch)               ;; orig. isearch-edit-string
     ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
     ("M-s L" . consult-line-multi))           ;; needed by consult-line to detect isearch
    :init
    ;; Optionally configure the register formatting. This improves the register
    ;; preview for `consult-register', `consult-register-load',
    ;; `consult-register-store' and the Emacs built-ins.
    (setq register-preview-delay 0
          register-preview-function #'consult-register-format)
  
    ;; Optionally tweak the register preview window.
    ;; This adds thin lines, sorting and hides the mode line of the window.
    (advice-add #'register-preview :override #'consult-register-window)
  
    ;; Optionally replace `completing-read-multiple' with an enhanced version.
    (advice-add #'completing-read-multiple :override #'consult-completing-read-multiple)
  
    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)
    :config
    (setq consult-narrow-key "<") ;; (kbd "C-+")
    (autoload 'projectile-project-root "projectile")
    (setq consult-project-root-function #'projectile-project-root)
  )
#+end_src

** Embark Consult
#+begin_src elisp
  ;; Consult users will also want the embark-consult package.
  (use-package embark-consult
    :after (embark consult)
    :demand t ; only necessary if you have the hook below
    ;; if you want to have consult previews as you move around an
    ;; auto-updating embark collect buffer
    :hook
    (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

** Wgrep
#+begin_src elisp
  (use-package wgrep
    :defer t
    :bind
    (:map
     grep-mode-map
     ("C-x C-q" . wgrep-change-to-wgrep-mode)
     ("C-c C-c" . wgrep-finish-edit)
     )
    )
#+end_src
* Parentheses
** Highlight parentheses
#+begin_src elisp
  (use-package highlight-parentheses
    :config
    (global-highlight-parentheses-mode)
    )
#+end_src

** Smartparens
#+begin_src elisp
  (use-package smartparens
    :config
    (smartparens-global-mode)
    )
#+end_src
* Org
** Org functions

[[id:22bbe957-46bb-4fb7-9601-ce7a07037198][Task management with org-roam Vol. 5: Dynamic and fast agenda]]Functions adapted from [[https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5][Task management with org-roam Vol. 5: Dynamic and fast agenda]]. Auto tagging is removed so that agenda files containing task clocks can be manually tagged so they show up in timeclocks.

#+begin_src elisp
  (defun vulpea-buffer-p ()
    "Return non-nil if the currently visited buffer is a note."
    (and buffer-file-name
         (string-prefix-p
          (expand-file-name (file-name-as-directory org-roam-directory))
          (file-name-directory buffer-file-name))))
  (defun vulpea-project-files ()
    "Return a list of note files containing 'project' tag." ;
    (seq-uniq
     (seq-map
      #'car
      (org-roam-db-query
       [:select [nodes:file]
                :from tags
                :left-join nodes
                :on (= tags:node-id nodes:id)
                :where (like tag (quote "%\"project\"%"))
                ]))))
  (defun vulpea-agenda-files-update (&rest _)
    "Update the value of `org-agenda-files'."
    (interactive)
    (setq org-agenda-files (vulpea-project-files)))
  (advice-add 'org-agenda :before #'vulpea-agenda-files-update)
  (advice-add 'org-dblock-update :before #'vulpea-agenda-files-update)
#+end_src

** Org mode
#+begin_src elisp :noweb yes
  (use-package org
    :bind 
    ("C-c l" . org-store-link)
    ("C-c a" . org-agenda)
    ("C-c c" . org-capture)
    :mode
    ("\\.\\(org\\|org_archive\\|txt\\)$" . org-mode)
    :hook
    (org-mode . (lambda () (set-fill-column 80)))
    (org-mode . visual-line-mode)
    :config
    <<org-config>>
    :custom
    <<org-custom>>
    )
#+end_src
** Org custom
#+begin_src elisp :tangle no :noweb-ref org-custom
  (org-directory "~/org/")
  (org-agenda-compact-blocks t)
  (org-agenda-custom-commands
   '(("h" "Agenda and home tasks"
      ((agenda "")
       (todo "NEXT" ((org-agenda-overriding-header "Next")))
       (todo "TODO" ((org-agenda-overriding-header "Todo")))
       (todo "WAITING" ((org-agenda-overriding-header "Waiting")))
       (todo "SOMETIME" ((org-agenda-overriding-header "Sometime")))
       ))
     )
    )
  (org-agenda-dim-blocked-tasks nil)
  (org-agenda-tags-todo-honor-ignore-options t)
  (org-agenda-todo-ignore-scheduled 'all)
  (org-agenda-todo-ignore-deadlines 'all)
  (org-duration-format (quote h:mm))
  (org-hide-emphasis-markers t)
  (org-log-done 'time)
  (org-log-into-drawer t)
  (org-outline-path-complete-in-steps nil)
  (org-refile-targets
   '(
     ("~/org/roam/daily/" . (:maxlevel . 3))
     ("~/org/roam/journal.org" . (:maxlevel . 3))
     ))
  (org-refile-use-outline-path t)
  (org-startup-indented t)
  (org-tag-alist
   '(
     ("@work" . ?w)
     ("@home" . ?h)
     ))
  (org-time-stamp-rounding-minutes (quote (0 1)))
  (org-todo-keywords
   '((sequence "TODO(t)" "NEXT(n)" "WAITING(w)" "SOMETIME(s)" "|" "DONE(d)" "CANCELLED(c)")))
  (org-todo-keyword-faces
   '(
     ("TODO" :foreground "red" :weight bold)
     ("NEXT" :foreground "light blue" :weight bold)
     ("WAITING" :foreground "orange" :weight bold)
     ("SOMETIME" :foreground "magenta" :weight bold)
     ("DONE" :foreground "forest green" :weight bold)
     ("CANCELLED" :foreground "forest green" :weight bold)
     ))
   ;; tasks tagged with 'project' are included in agenda
  (org-todo-state-tags-triggers
   '(
     (todo ("project" . t))
     (done ("project"))
     ))
#+end_src
** deft
#+begin_src elisp
  (use-package deft
    :bind ("<f8>" . deft)
    :commands deft
    :hook
    (deft-mode . (lambda () (set-fill-column 200)))
    :custom
    (deft-directory "~/org/")
    (deft-recursive t)
    (deft-use-filename-as-title nil)
    (deft-use-filter-string-for-filename t)
    (deft-auto-save-interval -1.0)
    (deft-file-naming-rules
     '(
       (noslash . "-")
       (nospace . "-")
       (case-fn . downcase)
       ))
    (deft-strip-summary-regexp
      (concat "\\("
              "[\n\t]" ;; blank
              "\\|^#\\+[[:alpha:]_]+:.*$" ;; org-mode metadata
              "\\|^:PROPERTIES:\n\\(.+\n\\)+:END:\n"
              "\\)"))
    :config
    (defun cm/deft-parse-title (file contents)
      (let ((begin (string-match "^#\\+[tT][iI][tT][lL][eE]: .*$" contents)))
        (if begin
            (string-trim (substring contents begin (match-end 0)) "#\\+[tT][iI][tT][lL][eE]: *" "[\n\t ]+")
          (deft-base-filename file)))
      )
    (advice-add 'deft-parse-title :override #'cm/deft-parse-title)
    )
#+end_src

** helm-org-rifle
#+begin_src elisp :tangle no
  (use-package helm-org-rifle)
#+end_src
** org-babel
#+begin_src elisp :tangle no :noweb-ref org-config
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (emacs-lisp . t)
     ;; (R . t)
     ;; (python .t)
     ;; (shell .t)
     ;; (org . t)
     )
   )
#+end_src

#+begin_src elisp :tangle no :noweb-ref org-custom
  (org-confirm-babel-evaluate nil)
#+end_src
** Org roam
#+begin_src elisp
  (use-package org-roam
    :after org
    :custom
    (org-roam-directory (file-truename "~/org/roam"))
    (org-roam-dailies-directory "daily/")
    (org-roam-capture-templates
     `(
       ("d" "default" plain "%?" 
        :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}")
        :unnarrowed t)
       ("a" "article" plain "%?"
        :target (file+head "%<%Y%m%d%H%M%S>-${citekey}.org"
                           ,(concat "#+title: ${title}\n"
                                    "#+filetags: :source:\n"
                                    "- date :: %U\n"
                                    "- author :: ${author-or-editor}\n"
                                    "- journal :: ${journal}\n"
                                    "- year :: ${year}\n"
                                    "- doi :: ${doi}\n\n"))
        :unnarrowed t)
       ("c" "company" plain "%?" 
        :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                           ,(concat "#+title: ${title}\n"
                                    "#+filetags: :company:\n"
                                    "- date :: %U\n"))
        :unnarrowed t)
       ("p" "person" plain "%?" 
        :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                           ,(concat "#+title: ${title}\n"
                                    "#+filetags: :person:\n"
                                    "- date :: %U\n"
                                    "- company :: \n"
                                    "- dob :: \n"
                                    "- interest :: \n"))
        :unnarrowed t)
       ))
    (org-roam-capture-ref-templates
     `(
       ("r" "ref" plain "%?"
        :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org"
                           ,(concat "#+title: ${title}\n"
                                    "#+filetags: :source:\n"
                                    "- date :: %U\n"
                                    "- author :: ${author-or-editor}\n"
                                    "- journal :: ${journal}\n"
                                    "- year :: ${year}\n\n"))
        :unnarrowed t)
       ))
    (org-roam-dailies-capture-templates
     '(
       ("d" "default" entry "* %?\n- date :: %U\n" :target
        (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n")
        )
       ("f" "fleeting note" entry "* %?  :fleeting:\n- date :: %U\n" :target
        (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n")
        )
       ("j" "journal" entry "* %U   :journal:\n%?" :target
        (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n")
        )
       ("t" "task" entry "* %?  :task:\n- date :: %U\n" :target
        (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n")
        )
       ("m" "meeting" entry "* %?  :meeting:\n- date :: %U\n- attendee :: John Lord\n- company :: \n- attendee :: \n- agenda :: \n\n" :target
        (file+head "%<%Y-%m-%d>.org" "#+title: %<%Y-%m-%d>\n")
        )
       ))
    :bind
    ("C-c n l" . org-roam-buffer-toggle)
    ("C-c n f" . org-roam-node-find)
    ("C-c n g" . org-roam-graph)
    ("C-c n i" . org-roam-node-insert)
    ("C-c n c" . org-roam-capture)
    ("C-c n o" . org-id-get-create)
    ("C-c n t" . org-roam-tag-add)
    ("C-c n r" . org-roam-ref-add)
    ("C-c n j" . org-roam-dailies-capture-today)
    ("C-c n d" . org-roam-dailies-capture-date)
    :hook
    (org-roam-mode . visual-line-mode)
    (org-capture-mode . org-align-all-tags)
    :init
    (setq org-roam-v2-ack t)
    (org-roam-db-autosync-mode)
    :config
    (require 'org-roam-protocol)
    ;; (add-to-list 'display-buffer-alist
    ;;              '("\\*org-roam\\*"
    ;;                (display-buffer-in-direction)
    ;;                (direction . right)
    ;;                (window-width . 0.33)
    ;;                (window-height . fit-window-to-buffer)))
    (add-to-list 'display-buffer-alist
                 '("\\*org-roam\\*"
                   (display-buffer-in-side-window)
                   (side . right)
                   (slot . 0)
                   (window-width . 0.33)
                   (window-parameters . ((no-other-window . t)
                                         (no-delete-other-windows . t)))))
    )
#+end_src

** org-ref
#+begin_src elisp
  (use-package org-ref
    :after org
    :custom
    (org-ref-notes-function 'orb-org-ref-edit)
    (org-ref-default-bibliography
     (list "~/git/bibliography/references.bib"))
    )
#+end_src

** helm-bibtex
#+begin_src elisp
  (use-package helm-bibtex
    :commands helm-bibtex
    :bind
    ("C-c n b" . helm-bibtex)
    :custom
    (bibtex-completion-pdf-field "file")
    (bibtex-completion-bibliography "~/git/bibliography/references.bib")
    )
#+end_src

** org-roam-bibtex
#+begin_src elisp
  (use-package org-roam-bibtex
    :after org-roam
    :custom
    (orb-preformat-keywords '("citekey" "title" "url" "file" "author-or-editor" "keywords" "doi" "date" "year" "journal" "journaltitle"))
    :hook
    (org-roam-mode . org-roam-bibtex-mode)
    :bind
    (:map org-mode-map
          ("C-c n a" . orb-note-actions)
          )
    )
#+end_src
* Beancount
#+begin_src elisp :tangle no
  (use-package beancount
    :straight (beancount
               :type git
               :host github
               :repo "beancount/beancount-mode")
    :mode ("\\.beancount\\'" . beancount-mode)
    :hook (beancount-mode . outline-minor-mode)
    :bind
    (:map beancount-mode-map
          ("C-j" . outline-next-visible-heading)
          ("C-k" . outline-previous-visible-heading)
          )
    )
#+end_src

* Mu4e
** Mu4e
#+begin_src elisp :noweb yes
  (use-package mu4e
    :ensure nil
    :load-path "/usr/local/share/emacs/site-lisp/mu4e"
    :commands mu4e
    :hook
    (mu4e-compose-mode . turn-off-auto-fill)
    (mu4e-compose-mode-hook . visual-line-mode)
    (mu4e-view-mode-hook . visual-line-mode)
    :custom
    <<mu4e-custom-vars>>
    :config
    <<mu4e-config>>
    (setq mu4e-contexts
     `(
       <<mu4e-context>>
       ))
    :init
    (require 'smtpmail)
    )
#+END_SRC

#+begin_src elisp :tangle no :noweb-ref mu4e-config
  (defun my-remove-attachment (msg num)
    "Remove attachment."
    (let*
        (
         (attach (mu4e~view-get-attach msg num))
         (path (mu4e-msg-field msg :path))
         (filename (and attach (plist-get attach :name)))
         (cmd (format "altermime --input='%s' --remove='%s'"  path filename)))
      (when (and filename
                 (yes-or-no-p
                  (format "Are you sure you want to remove '%s'?" filename)))
        (shell-command cmd)
        (message cmd))))
  (add-to-list 'mu4e-view-actions '("ViewInBrowser" . mu4e-action-view-in-browser) t)
  (add-to-list 'mu4e-view-attachment-actions '("remove-attachment" . my-remove-attachment))
  (advice-add #'shr-colorize-region :around (defun shr-no-colourise-region (&rest ignore)))
#+end_src

** Mu4e custom set variables
#+begin_src elisp :tangle no :noweb-ref mu4e-custom-vars
  (mail-user-agent 'mu4e-user-agent)
  (message-kill-buffer-on-exit t)
  (message-send-mail-function 'smtpmail-send-it)
  (mu4e-change-filenames-when-moving t)
  ;;(mu4e-completing-read-function 'ivy-completing-read)
  (mu4e-compose-dont-reply-to-self t)
  (mu4e-compose-format-flowed t)
  (mu4e-compose-in-new-frame t)
  (mu4e-compose-signature "John Lord\nTel: +1-512-550-4917")
  (mu4e-attachment-dir "~/Downloads")
  (mu4e-enable-mode-line t)
  (mu4e-flowed-encode-column 998)
  (mu4e-get-mail-command "mbsync -a")
  (mu4e-headers-date-format "%Y-%m-%d")
  (mu4e-headers-auto-update t)
  (mu4e-headers-fields
   '(
     (:human-date . 12)
     (:flags . 6)
     (:mailing-list . 10)
     (:from-or-to . 22)
     (:subject)
     ))
  (mu4e-org-link-query-in-headers-mode nil)
  (mu4e-sent-messages-behavior 'delete)
  (mu4e-sent-folder   "/lordsonline/[Gmail].Sent Mail")       ;; sent messages
  (mu4e-drafts-folder "/lordsonline/[Gmail].Drafts")     ;; unfinished messages
  (mu4e-trash-folder  "/lordsonline/[Gmail].Trash")      ;; trashed messages
  (mu4e-refile-folder "/lordsonline/[Gmail].All Mail")   ;; saved messages
  (mu4e-update-interval 180)
  (mu4e-view-html-plaintext-ratio-heuristic most-positive-fixnum)
  (mu4e-view-show-images t)
  (send-mail-function 'smtpmail-send-it)
  (shr-color-visible-distance-min 5)
  (shr-color-visible-luminance-min 60)
  (shr-use-colors nil)
  (smtpmail-queue-mail nil)
#+end_src
** Mu4e contexts
*** Lordsonline context
#+begin_src elisp :tangle no :noweb-ref mu4e-context
  ,(make-mu4e-context
    :name "Lordsonline"
    :enter-func (lambda () (mu4e-message "Entering Lordsonline context"))
    :leave-func (lambda () (mu4e-message "Leaving Lordsonline context"))
    ;; we match based on the maildir of the message
    :match-func (lambda (msg)
                  (when msg
                    (string-prefix-p "/lordsonline" (mu4e-message-field msg :maildir))))
    :vars
    '(
      (user-mail-address . "john@lordsonline.org")
      (user-full-name . "John Lord")
      (org-msg-signature . "\n\nBest regards,\n\nJohn\n ,#+begin_signature\n--\n,*John Lord* \\\\\nTel: /+1-512-550-4917/\n,#+end_signature"
                         )
      (mu4e-drafts-folder . "/lordsonline/[Gmail].Drafts")
      (mu4e-sent-folder   . "/lordsonline/[Gmail].Sent Mail")
      (mu4e-trash-folder  . "/lordsonline/[Gmail].Trash")
      (mu4e-refile-folder . "/lordsonline/[Gmail].All Mail")
      (mu4e-maildir-shortcuts
       . (
          (:maildir "/lordsonline/INBOX"              :key ?i)
          (:maildir "/lordsonline/[Gmail].Sent Mail"  :key ?s)
          (:maildir "/lordsonline/[Gmail].Trash"      :key ?t)
          (:maildir "/lordsonline/[Gmail].Drafts"     :key ?d)
          (:maildir "/lordsonline/[Gmail].All Mail"   :key ?a)
          (:maildir "/archive"                        :key ?A)
          )
       )
      (smtpmail-queue-dir . "~/Maildir/lordsonline/queue/cur")
      (smtpmail-smtp-user . "john@lordsonline.org")
      (smtpmail-smtp-server . "smtp.gmail.com")
      (smtpmail-smtp-service . 587)
      )
    )
#+end_src
*** iCloud context
#+begin_src elisp :tangle no :noweb-ref mu4e-context
  ,(make-mu4e-context
    :name "iCloud"
    :enter-func (lambda () (mu4e-message "Entering iCloud context"))
    :leave-func (lambda () (mu4e-message "Leaving iCloud context"))
    ;; we match based on the maildir of the message
    :match-func (lambda (msg)
                  (when msg
                    (string-prefix-p "/icloud" (mu4e-message-field msg :maildir))))
    :vars
    '(
      (user-mail-address . "lordjd@icloud.com")
      (user-full-name . "John Lord")
      (org-msg-signature . "\n\nBest regards,\n\nJohn\n ,#+begin_signature\n--\n,*John Lord* \\\\\nTel: /+1-512-550-4917/\n,#+end_signature"
                         )
      (mu4e-drafts-folder . "/icloud/Drafts")
      (mu4e-sent-folder   . "/icloud/Sent")
      (mu4e-trash-folder  . "/icloud/Trash")
      (mu4e-refile-folder . "/icloud/Archive")
      (mu4e-maildir-shortcuts
       . (
          (:maildir "/icloud/INBOX"              :key ?i)
          (:maildir "/icloud/Sent"               :key ?s)
          (:maildir "/icloud/Trash"              :key ?t)
          (:maildir "/icloud/Drafts"             :key ?d)
          (:maildir "/icloud/Archive"            :key ?a)
          (:maildir "/archive"                   :key ?A)
          )
       )
      (smtpmail-queue-dir . "~/Maildir/lordsonline/queue/cur")
      (smtpmail-smtp-user . "john")
      (smtpmail-smtp-server . "smtp.gmail.com")
      (smtpmail-smtp-service . 587)
      )
    )
#+end_src
*** Outlook context
#+begin_src elisp :tangle no :noweb-ref mu4e-context
  ,(make-mu4e-context
    :name "Outlook"
    :enter-func (lambda () (mu4e-message "Entering outlook context"))
    :leave-func (lambda () (mu4e-message "Leaving outlook context"))
    ;; we match based on the maildir of the message
    :match-func (lambda (msg)
                  (when msg
                    (string-prefix-p "/outlook" (mu4e-message-field msg :maildir))))
    :vars
    '(
      (user-mail-address . "lordjd@outlook.com")
      (user-full-name . "John Lord")
      (org-msg-signature . "\n\nBest regards,\n\nJohn\n ,#+begin_signature\n--\n,*John Lord* \\\\\nTel: /+1-512-550-4917/\n,#+end_signature"
                         )
      (mu4e-drafts-folder . "/outlook/Drafts")
      (mu4e-sent-folder   . "/outlook/Sent")
      (mu4e-trash-folder  . "/outlook/Trash")
      (mu4e-refile-folder . "/outlook/Archive")
      (mu4e-maildir-shortcuts
       . (
          (:maildir "/outlook/INBOX"              :key ?i)
          (:maildir "/outlook/Sent"               :key ?s)
          (:maildir "/outlook/Trash"              :key ?t)
          (:maildir "/outlook/Drafts"             :key ?d)
          (:maildir "/outlook/Archive"            :key ?a)
          (:maildir "/archive"                    :key ?A)
          )
       )
      (smtpmail-queue-dir . "~/Maildir/lordsonline/queue/cur")
      (smtpmail-smtp-user . "john")
      (smtpmail-smtp-server . "smtp.gmail.com")
      (smtpmail-smtp-service . 587)
      )
    )
#+end_src
*** Archive context
#+begin_src elisp :tangle no :noweb-ref mu4e-context
  ,(make-mu4e-context
    :name "Archive"
    :enter-func (lambda () (mu4e-message "Entering archive context"))
    :leave-func (lambda () (mu4e-message "Leaving archive context"))
    ;; we match based on the maildir of the message
    :match-func (lambda (msg)
                  (when msg
                    (string-prefix-p "/archive" (mu4e-message-field msg :maildir))))
    :vars
    '(
      (user-mail-address . "john@lordsonline.org")
      (user-full-name . "John Lord")
      (mu4e-maildir-shortcuts
       . (
          (:maildir "/archive"                  :key ?a)
          )
       )
      )
    )
#+end_src
*** Protonmail context
#+begin_src elisp :tangle no :noweb-ref mu4e-context
  ,(make-mu4e-context
    :name "P ProtonMail"
    :enter-func (lambda () (mu4e-message "Entering ProtonMail context"))
    :leave-func (lambda () (mu4e-message "Leaving ProtonMail context"))
    :match-func (lambda (msg)
                  (when msg
                    (string-prefix-p "/protonmail" (mu4e-message-field msg :maildir))))
    :vars '(
            (user-mail-address . "john@lordpharmaconsulting.com")
            (user-full-name . "John Lord")
            (org-msg-signature . "\n\nBest regards,\n\nJohn
    ,,#+begin_signature
    -- 
    ,,*John Lord* \\\\
    Tel (US): /+1-512-550-4917/
    ,,#+end_signature"
                               )
            (mu4e-drafts-folder . "/protonmail/Drafts")
            (mu4e-sent-folder   . "/protonmail/Sent")
            (mu4e-trash-folder  . "/protonmail/Trash")
            (mu4e-refile-folder . "/protonmail/Archive")
            (mu4e-maildir-shortcuts
             . (
                (:maildir "/protonmail/INBOX"     :key ?i)
                (:maildir "/protonmail/Sent"      :key ?s)
                (:maildir "/protonmail/Trash"     :key ?t)
                (:maildir "/protonmail/Archive"   :key ?a)
                (:maildir "/archive"              :key ?A)
                )
             )
            (smtpmail-queue-dir . "~/Maildir/protonmail/queue/cur")
            (smtpmail-smtp-user . "lordjd1@pm.me")
            (smtpmail-smtp-server . "127.0.0.1")
            (smtpmail-smtp-service . 1025)
            )
    )
#+end_src
** Mu4e bookmarks

#+begin_src elisp :tangle no :noweb-ref mu4e-config
  (add-to-list 'mu4e-bookmarks
               '( :name  "Business messages"
                         :query "from:john@lordpharma.com or to:john@lordpharma.com or cc:john@lordpharma.com or bcc:john@lordpharma.com or from:john@lordpharmaconsulting.com or to:john@lordpharmaconsulting.com or cc:john@lordpharmaconsulting.com or bcc:john@lordpharmaconsulting.com"
                         :key   ?b)
               t)
#+end_src

** Org msg
#+name: org-msg
#+begin_src elisp :tangle no
  (use-package org-msg
    :after mu4e 
    :config
    (setq
     org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \\n:t"
     org-msg-startup "hidestars indent inlineimages"
     org-msg-greeting-fmt "\nHi %s,\n\n"
     org-msg-recipient-names '(("john@lordsonline.org" . "John Lord"))
     org-msg-greeting-name-limit 3
     org-msg-default-alternatives '(text html)
     org-msg-convert-citation t
     )
    (org-msg-mode)
    )
#+end_src

* Magit
#+begin_src elisp
  (use-package magit
    :defer t
    )
#+end_src

* Dired
** Dired variables
#+begin_src elisp
  (use-package dired
    ;; :hook
    ;; (dired-mode . evil-mode)
    :ensure nil
    :custom
    (dired-listing-switches "-alh -v --group-directories-first")
    (dired-auto-revert-buffer t)
    (dired-dwim-target t)
    (dired-hide-details-hide-symlink-targets nil)
    (dired-recursive-copies  'always)
    (dired-recursive-deletes 'top)
    (dired-create-destination-dirs 'ask)
    (image-dired-thumb-size 150)
    )
#+end_src

** Peep dired
#+begin_src elisp
  (use-package peep-dired
    :custom
    (peep-dired-cleanup-on-disable t)
    ;; :hook
    ;; (peep-dired . evil-normalize-keymaps)
    ;; :config
    ;; (evil-define-key 'normal peep-dired-mode-map
    ;;   (kbd "<SPC>") 'peep-dired-scroll-page-down
    ;;   (kbd "C-<SPC>") 'peep-dired-scroll-page-up
    ;;   (kbd "<backspace>") 'peep-dired-scroll-page-up
    ;;   (kbd "j") 'peep-dired-next-file
    ;;   (kbd "k") 'peep-dired-prev-file)
  )
#+end_src

** Dired rsync
#+begin_src elisp
  (use-package dired-rsync
    :bind
    (:map dired-mode-map
          ("C-c C-r" . dired-rsync))
    ) 
#+end_src

** Diredfl
#+begin_src elisp
  (use-package diredfl
    :hook
    (dired-mode . diredfl-mode)
    ) 
#+end_src

* Latex
#+name: auctex
#+begin_src elisp :tangle no
  (use-package auctex
    :ensure t
    :defer t
    :config
    (setq TeX-auto-save t
          TeX-parse-self t)
    (setq-default TeX-engine 'xetex)
    )
#+end_src

#+name: moderncv
#+begin_src elisp :tangle no 
  ;; (use-package general
  ;; (use-package ox-moderncv
  ;;   :straight (ox-moderncv :type git :host gitlab :repo "Titan-C/org-cv")
  ;;   :init (require 'ox-moderncv)
  ;;   )
#+end_src

* Python
#+name: python
#+begin_src elisp :tangle no
  (use-package elpy
    :init
    (elpy-enable)
    :config
    (setq python-indent-offset 4)
    (setenv "WORKON_HOME" "~/src")
    (setq python-shell-interpreter "jupyter"
          python-shell-interpreter-args "console --simple-prompt"
          python-shell-prompt-detect-failure-warning nil)
    (add-to-list 'python-shell-completion-native-disabled-interpreters
                 "jupyter")
    )
#+end_src

#+name: ein
#+begin_src elisp :tangle no
  (use-package ein
    :ensure t
   ) 
#+end_src

* Yaml
** Yaml
#+begin_src elisp
  (use-package yaml-mode
    :defer t)
#+end_src

* Terminals
** Vterm
#+begin_src elisp
  (use-package vterm
    :defer t
    ) 
#+end_src




